services:
  navigation:
    build:
      context: ./navigation
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: postgresql-docker
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    build: .
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  navigation-ui:
    build:
      context: ./navigation-ui
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - navigation

networks:
  app-network:
    driver: bridge