services:
  navigation:
    build:
      context: ./navigation
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  navigation-ui:
    build:
      context: ./navigation-ui
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - navigation

networks:
  app-network:
    driver: bridge
