CREATE TABLE EDGE (
                      DIRECTION INTEGER NOT NULL,
                      DISTANCE INTEGER NOT NULL,
                      TYPE SMALLINT,
                      ID BIGSERIAL PRIMARY KEY,
                      VERTEX1_ID BIGINT,
                      VERTEX2_ID BIGINT
);

CREATE TABLE SCHEME (
                        ID BIGSERIAL PRIMARY KEY,
                        LEVEL BIGINT,
                        DESCRIPTION VARCHAR(255)
);

CREATE TABLE SCHEME_EDGES (
                              EDGE_ID BIGINT NOT NULL,
                              SCHEME_ID BIGINT NOT NULL
);

CREATE TABLE SCHEME_SUB_SCHEME_IDS (
                                       SCHEME_ID BIGINT NOT NULL,
                                       SUB_SCHEME_ID BIGINT
);

CREATE TABLE SCHEME_VERTEXES (
                                 SCHEME_ID BIGINT NOT NULL,
                                 VERTEX_ID BIGINT NOT NULL
);

CREATE TABLE VERTEX (
                        AVAILABILITY BOOLEAN,
                        TYPE SMALLINT,
                        ID BIGSERIAL PRIMARY KEY,
                        DESCRIPTION VARCHAR(255),
                        NAME VARCHAR(255)
);

CREATE TABLE VERTEX_ANGLES (
                               ANGLES INTEGER,
                               ANGLES_KEY BIGINT NOT NULL,
                               VERTEX_ID BIGINT NOT NULL,
                               PRIMARY KEY (ANGLES_KEY, VERTEX_ID)
);


ALTER TABLE EDGE ADD CONSTRAINT CHECK_TYPE_EDGE CHECK (TYPE BETWEEN 0 AND 1);
ALTER TABLE VERTEX ADD CONSTRAINT CHECK_TYPE_VERTEX CHECK (TYPE BETWEEN 0 AND 2);

ALTER TABLE EDGE ADD CONSTRAINT FK_EDGE_VERTEX1 FOREIGN KEY (VERTEX1_ID) REFERENCES VERTEX (ID);
ALTER TABLE SCHEME_VERTEXES ADD CONSTRAINT FK_SCHEME_VERTEXES_SCHEME FOREIGN KEY (SCHEME_ID) REFERENCES SCHEME (ID);
ALTER TABLE SCHEME_SUB_SCHEME_IDS ADD CONSTRAINT FK_SCHEME_SUB_SCHEME_IDS_SCHEME FOREIGN KEY (SCHEME_ID) REFERENCES SCHEME (ID);
ALTER TABLE SCHEME_EDGES ADD CONSTRAINT FK_SCHEME_EDGES_SCHEME FOREIGN KEY (SCHEME_ID) REFERENCES SCHEME (ID);
ALTER TABLE SCHEME_EDGES ADD CONSTRAINT FK_SCHEME_EDGES_EDGE FOREIGN KEY (EDGE_ID) REFERENCES EDGE (ID);
ALTER TABLE VERTEX_ANGLES ADD CONSTRAINT FK_VERTEX_ANGLES_VERTEX FOREIGN KEY (VERTEX_ID) REFERENCES VERTEX (ID);
ALTER TABLE EDGE ADD CONSTRAINT FK_EDGE_VERTEX2 FOREIGN KEY (VERTEX2_ID) REFERENCES VERTEX (ID);
