INSERT INTO VERTEX (ID, NAME, DESCRIPTION, TYPE , LEVEL, AVAILABILITY) VALUES
    (1, '111', '111 cabinet', 'cabinet', 1, TRUE);
INSERT INTO VERTEX (ID, NAME, DESCRIPTION, TYPE , LEVEL, AVAILABILITY) VALUES
    (2, '112', '112 cabinet', 'cabinet', 1, TRUE);
INSERT INTO VERTEX (ID, NAME, DESCRIPTION, TYPE , LEVEL, AVAILABILITY) VALUES
    (3, '113', '113 cabinet', 'cabinet', 1, TRUE);
INSERT INTO VERTEX (ID, NAME, DESCRIPTION, TYPE , LEVEL, AVAILABILITY) VALUES
    (4, '114', '114 cabinet', 'cabinet', 1, TRUE);
INSERT INTO VERTEX (ID, NAME, DESCRIPTION, TYPE , LEVEL, AVAILABILITY) VALUES
    (5, 'crossroad', 'big crossroad', 'crossroad', 1, TRUE);